name: broaden
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.0.1
  location: ^2.5.0
  font_awesome_flutter: ^8.12.0
  http: ^0.12.2
  camera: ^0.5.2+1

  path_provider: ^1.1.0
  path: ^1.6.2

  # geolocator: ^7.0.1
  geolocator: ^6.2.1

  # Firebase
  firebase_core: "0.5.3"
  firebase_auth: ^0.18.4+1

  provider: ^4.3.2+3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

 